name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run flake8 linter
        run: |
          flake8 .

      - name: Run script.py
        run: |
          python script.py

      - name: Run tests with pytest
        run: |
          pytest > result.log

      - name: Upload test result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: result.log
